server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  level:
    org.apache.pulsar.shade.org.asynchttpclient.netty.channel: info

pulsar:
  url:
  topics:
  cluster-id:
  namespace:
  token:

tencent:
  secret-id:
  secret-key:
  cos-region:
  bucket-name:
  folder: avatars

push:
  url: