server:
  port: 811

spring:
  datasource:
    url: jdbc:h2:file:./db/db_helper_hub;auto_server=true;db_close_on_exit=false
    username:
    password:
    schema: classpath:sql/schema.sql
    driver-class-name: org.h2.Driver
  h2:
   console:
     enabled: true
     path: /h2
     settings:
       web-allow-others: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml

task:
  cron: 0 21 1 * * ?