server:
  port: 811

spring:
  data:
    mongodb:
      uri: mongodb://cruii:970811@aliyun:27017/helperhub
  datasource:
    url: jdbc:h2:file:./db/db_helper_hub;auto_server=true;db_close_on_exit=false
    username:
    password:
    schema: classpath:sql/schema.sql
    driver-class-name: org.h2.Driver
  h2:
   console:
     enabled: true
     path: /h2
     settings:
       web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

logging:
  config: classpath:logback-spring.xml