name: Automatic Releases

on:
  push:
    paths:
      - '**/*src/**/version.properties'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression='project.version' -q -DforceStdout)" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
            repo_token: "${{ secrets.GH_TOKEN }}"
            automatic_release_tag: "v${{ env.RELEASE_VERSION }}"
            prerelease: false
            title: "v${{ env.RELEASE_VERSION }}"
