name: Deploy to server

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      - name: Deploy with SSH
        uses: garygrossgarten/github-action-scp@release
        with:
          local: "./hh-web/target/*.jar,./hh-execution/target/*.jar,./hh-push/target/*.jar,./hh-gateway/target/*.jar"
          remote: /root/app/ohmyhelper/
          host: ${{ secrets.DEPLOY_SERVER_IP }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
